### ISSUE TITLE
Use rustyline for shell

### ISSUE THREAD

**Issue by Geemili** [sagebind/riptide#5]
The [rustyline][] library implements history, word completion, multiple lines,
etc. I'm not sure if it would be a good idea to use it in a project that wants 
to become it's own shell, but it would be a significant step up in features for 
riptide currently. 

I'm willing to do some of the legwork here, but I want to know if there's a 
reason not to before I do. 

[rustyline]: https://github.com/kkawakam/rustyline

**Comment by sagebind** [comment]
Thanks for your interest in Riptide, you're like one of the first!

At one point in history the shell did use RustyLine. It was really great to work with. I pivoted away though because I'm planning the following features that are not currently compatible with RustyLine (and probably won't ever be):

- Multi-line editing like Fish shell: Pressing the enter key only runs the command if it is complete (curly braces are balanced, etc.), otherwise it inserts a newline into the command buffer. Only the Riptide parser can provide this information.
- User-defined key bindings. Even bindings for the command buffer should be customizable by the user.
- Potentially a built-in cusrses-like interface for some things like settings management, etc. Maybe even a status bar like tmux. This part is a bit fuzzy yet.

Also I wouldn't put too much effort into the shell aspect yet, as the interpreter itself still has a ways to go...

**Comment by Geemili** [comment]
Ah, okay, good to know. I'll go ahead and close the issue then. Thanks for the response!
